version: '3'
services:
  hopeful-ai:
    build:
      context: ./stub-third-parties/hopeful-ai
    ports:
      - 3003:3003
    environment:
      - PORT=3002
      - MIN_RESPONSE_TIME=1000
      - MAX_RESPONSE_TIME=2000
      - SUCCESS_RATE=1
  rapid-ai:
    build:
      context: ./stub-third-parties/rapid-ai
    ports:
      - 3003:3003
    environment:
      - PORT=3003
      - MIN_RESPONSE_TIME=500
      - MAX_RESPONSE_TIME=2000
      - SUCCESS_RATE=0.95